---
- name: install epel-release
  yum: name=epel-release state=present

- name: install nginx
  yum: name=nginx state=present

- name: copy the webpages
  copy: src=webpages/ dest=/var/www/html/
  
- name: copy the hostfile
  template: src=hostfile.j2 dest=/etc/hosts

- name: copy the nginx file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

